### ISSUE TITLE
Chrome removes this extension after each restart

### ISSUE THREAD

**Issue by vemfanvet** [ncla/SteamInventoryExpert#5]
Is there any way to fix this without submitting it to the chrome store?

**Comment by Momchoto** [comment]
What do you mean? How does it remove it and why do you have to submit it to the store?

**Comment by vemfanvet** [comment]
Every time I launch chrome it tells me that it's an unofficial extension that's not from the chrome store, therefor it has automatically been removed

**Comment by Momchoto** [comment]
Hmm, i have no idea what is causing this, maybe try to enable Developer mode.

**Comment by ncla** [comment]
AFAIK this should not happen if you have Developer Mode enabled. I still however do get prompted every start of Chrome that I have developer extensions installed and whether or not I would like to remove them. You can not disable it sadly, but you should be able to preserve the extension through restarts.

**Comment by KIPdeKIP** [comment]
This still happens with Developer Mode enabled. Whenever you restart the browser it forcibly disables the extension.

https://productforums.google.com/forum/#!topic/chrome/2yTVWdfC4Gg

http://www.alphr.com/news/security/388957/google-cracks-down-on-unofficial-chrome-extensions

https://github.com/YePpHa/YouTubeCenter/issues/524

**Comment by ncla** [comment]
@KIPdeKIP Not sure why it doesn't happen to me then. I am on stable version of Chrome, however I do have Beta version installed along side. Maybe that helps?

**Comment by Momchoto** [comment]
Hmm, maybe try to reinstall it, developer mode has to work, at least it worked for me when i tried it.
Also i stopped using this version because it wasn't showing items already in a trade, so i downloaded the official extension as a .crx, unpacked it, searched "csgofast" in all the files and deleted everything associated with it. There was no malware, only external prices from CSGOFAST.com and a few banners. Unfortunately i deleted a bit too much and some of the things stopped working, so i redownloaded it, ONLY removed the banners, and disabled auto-updating. Works good now.
You can also try doing something like this
http://screencast.com/t/WddP13dW08
